version: "3.3"

services:
  server:
    container_name: server
    image: nestjs-api:1.0.0
    build: ./server
    ports:
      - 3000:3000
      - 3010:3010
    environment:
      - DB_URL=mongodb://db_mongo
    volumes:
      - ./server/UserService:/app/UserService
      - ./server/AuthService:/app/AuthService
      - /app/AuthService/node_modules
      - /app/UserService/node_modules
    command: npm run start
    restart: always

  mongo:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    restart: always
    ports:
      - "27017:27017"
volumes:
  mongodata:
